name: Daily Thribee BigQuery Push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      THRIBEE_EMAIL: ${{ secrets.THRIBEE_EMAIL }}
      THRIBEE_PASSWORD: ${{ secrets.THRIBEE_PASSWORD }}
      GOOGLE_APPLICATION_CREDENTIALS: ./secrets/bigquery-creds.json
      GA4_CREDENTIALS: ./secrets/client_secret.json
      GA4_TOKEN: ./secrets/token.pickle

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Prepare secrets
        run: |
          mkdir -p secrets
          echo "${{ secrets.BQ_DB_JSON }}" > secrets/bq_db.json
          echo "${{ secrets.CLIENT_SECRET_JSON }}" > secrets/client_secret.json
          echo "${{ secrets.GA4_TOKEN_BASE64 }}" | base64 -d > secrets/token.pickle

      - name: Inspect bq_db.json (sanitized)
        run: |
          echo "-------- START OF FILE --------"
          head -n 20 secrets/bq_db.json | sed 's/"private_key": "[^"]\+"/"private_key": "***REDACTED***"/g'
          echo "--------- END OF FILE ---------"

      - name: Validate JSON format
        run: python -m json.tool < secrets/bq_db.json

      - name: Run the script
        run: python main.py
